export const chats = [
  {
    id: 1,
    name: 'Alice Johnson',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',
    createdAt: '2024-01-15T08:35:30Z',
    email: 'alice.johnson@example.com',
    phone: '+1 234 567 8901',
    messages: [
      {
        id: 1,
        content: 'Hello, everyone!',
        createdAt: '2024-01-15T08:35:30Z',
        sentBy: 'Alice Johnson',
      },
      {
        id: 2,
        content: 'Hi Alice! How are you doing?',
        createdAt: '2024-01-15T08:36:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'I’m good, thanks! Just looking forward to the weekend.',
        createdAt: '2024-01-15T08:37:15Z',
        sentBy: 'Alice Johnson',
      },
      {
        id: 4,
        content: 'Same here! Any plans?',
        createdAt: '2024-01-15T08:38:05Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Maybe a hike or some time at the beach. You?',
        createdAt: '2024-01-15T08:39:25Z',
        sentBy: 'Alice Johnson',
      },
      {
        id: 6,
        content: 'That sounds fun! I might just relax at home.',
        createdAt: '2024-01-15T08:40:30Z',
        sentBy: 'John Doe',
      },
    ],
  },
  {
    id: 2,
    name: 'Bob Smith',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
    createdAt: '2024-02-03T13:22:10Z',
    email: 'bob.smith@example.com',
    phone: '+1 234 567 8902',
    messages: [
      { id: 1, content: 'Hey Alice!', createdAt: '2024-02-03T13:22:10Z', sentBy: 'Bob Smith' },
      {
        id: 2,
        content: 'Hey Bob! Any plans for tonight?',
        createdAt: '2024-02-03T13:22:50Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Not yet! Was thinking of going out. Want to join?',
        createdAt: '2024-02-03T13:23:40Z',
        sentBy: 'Bob Smith',
      },
      {
        id: 4,
        content: 'Sure, sounds like a plan! What time?',
        createdAt: '2024-02-03T13:24:20Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Let’s meet around 7. I’ll send the details later.',
        createdAt: '2024-02-03T13:25:30Z',
        sentBy: 'Bob Smith',
      },
      {
        id: 6,
        content: 'Perfect! See you then.',
        createdAt: '2024-02-03T13:26:00Z',
        sentBy: 'John Doe',
      },
    ],
  },
  {
    id: 3,
    name: 'Charlie Green',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
    createdAt: '2024-02-10T18:45:55Z',
    email: 'charlie.green@example.com',
    phone: '+1 234 567 8903',
    messages: [
      {
        id: 1,
        content: 'Good morning, team!',
        createdAt: '2024-02-10T18:45:55Z',
        sentBy: 'Charlie Green',
      },
      {
        id: 2,
        content: 'Hey Charlie! How’s the project going?',
        createdAt: '2024-02-10T18:46:30Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Just finished it! Took longer than I thought.',
        createdAt: '2024-02-10T18:47:00Z',
        sentBy: 'Charlie Green',
      },
      {
        id: 4,
        content: 'Awesome! Can’t wait to see it.',
        createdAt: '2024-02-10T18:48:15Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'I’ll send it over later today.',
        createdAt: '2024-02-10T18:49:45Z',
        sentBy: 'Charlie Green',
      },
    ],
  },
  {
    id: 4,
    name: 'Diana Rose',
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
    createdAt: '2024-03-25T14:12:34Z',
    email: 'diana.rose@example.com',
    phone: '+1 234 567 8904',
    messages: [
      {
        id: 1,
        content: 'Hi John! I need some help with this task.',
        createdAt: '2024-03-25T14:12:34Z',
        sentBy: 'Diana Rose',
      },
      {
        id: 2,
        content: 'Hey Diana, sure! What do you need?',
        createdAt: '2024-03-25T14:13:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Could you review my report? I’m not sure about some details.',
        createdAt: '2024-03-25T14:14:20Z',
        sentBy: 'Diana Rose',
      },
      {
        id: 4,
        content: 'Of course, send it over and I’ll take a look.',
        createdAt: '2024-03-25T14:15:00Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Thank you so much, John!',
        createdAt: '2024-03-25T14:16:25Z',
        sentBy: 'Diana Rose',
      },
    ],
  },
  {
    id: 5,
    name: 'Evan Lee',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
    createdAt: '2024-04-07T09:30:45Z',
    email: 'evan.lee@example.com',
    phone: '+1 234 567 8905',
    messages: [
      {
        id: 1,
        content: 'Good to see everyone here.',
        createdAt: '2024-04-07T09:30:45Z',
        sentBy: 'Evan Lee',
      },
      {
        id: 2,
        content: 'Hey Evan! Any updates on the project?',
        createdAt: '2024-04-07T09:31:15Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'We’re making progress! Still need a few more days.',
        createdAt: '2024-04-07T09:32:05Z',
        sentBy: 'Evan Lee',
      },
      {
        id: 4,
        content: 'Good to hear. Let me know if you need help.',
        createdAt: '2024-04-07T09:32:45Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Will do, thanks John!',
        createdAt: '2024-04-07T09:33:25Z',
        sentBy: 'Evan Lee',
      },
    ],
  },
  {
    id: 6,
    name: 'Fiona Gray',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
    createdAt: '2024-05-11T10:21:55Z',
    email: 'fiona.gray@example.com',
    phone: '+1 234 567 8906',
    messages: [
      { id: 1, content: 'Hey team!', createdAt: '2024-05-11T10:21:55Z', sentBy: 'Fiona Gray' },
      {
        id: 2,
        content: 'Hey Fiona! How’s everything going?',
        createdAt: '2024-05-11T10:22:20Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Going well! I’ll be online later today if anyone needs me.',
        createdAt: '2024-05-11T10:23:00Z',
        sentBy: 'Fiona Gray',
      },
      {
        id: 4,
        content: 'Got it! Let’s catch up then.',
        createdAt: '2024-05-11T10:24:10Z',
        sentBy: 'John Doe',
      },
      { id: 5, content: 'Sounds good!', createdAt: '2024-05-11T10:25:15Z', sentBy: 'Fiona Gray' },
    ],
  },
  {
    id: 7,
    name: 'George Wilson',
    image: 'https://randomuser.me/api/portraits/men/4.jpg',
    createdAt: '2024-06-14T16:05:21Z',
    email: 'george.wilson@example.com',
    phone: '+1 234 567 8907',
    messages: [
      { id: 1, content: 'Hi all!', createdAt: '2024-06-14T16:05:21Z', sentBy: 'George Wilson' },
      {
        id: 2,
        content: 'Hey George! How’s it going?',
        createdAt: '2024-06-14T16:05:50Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'All good here. I’m excited for the new update!',
        createdAt: '2024-06-14T16:06:35Z',
        sentBy: 'George Wilson',
      },
      {
        id: 4,
        content: 'Me too! Should be great.',
        createdAt: '2024-06-14T16:07:05Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Absolutely! Let’s chat soon.',
        createdAt: '2024-06-14T16:08:00Z',
        sentBy: 'George Wilson',
      },
    ],
  },
  {
    id: 8,
    name: 'Hannah Lee',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
    createdAt: '2024-07-09T12:22:15Z',
    email: 'hannah.lee@example.com',
    phone: '+1 234 567 8908',
    messages: [
      { id: 1, content: 'Hey, John!', createdAt: '2024-07-09T12:22:15Z', sentBy: 'Hannah Lee' },
      {
        id: 2,
        content: 'Hi Hannah! Need anything?',
        createdAt: '2024-07-09T12:23:05Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Just wanted to catch up. How’s work going?',
        createdAt: '2024-07-09T12:23:45Z',
        sentBy: 'Hannah Lee',
      },
      {
        id: 4,
        content: 'Going well, thanks! Busy as usual.',
        createdAt: '2024-07-09T12:24:25Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Glad to hear! Catch you later.',
        createdAt: '2024-07-09T12:25:00Z',
        sentBy: 'Hannah Lee',
      },
    ],
  },
  {
    id: 9,
    name: 'Yara Kim',
    image: 'https://randomuser.me/api/portraits/women/11.jpg',
    createdAt: '2024-11-07T10:15:20Z',
    email: 'yara.kim@example.com',
    phone: '+1 234 567 8911',
    messages: [
      {
        id: 1,
        content: 'Hi John! Do you have a minute to chat?',
        createdAt: '2024-11-07T10:15:20Z',
        sentBy: 'Yara Kim',
      },
      {
        id: 2,
        content: 'Hey Yara! Sure, what’s up?',
        createdAt: '2024-11-07T10:16:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content:
          'I had a question about the presentation slides. Do you think we need more visuals?',
        createdAt: '2024-11-07T10:16:45Z',
        sentBy: 'Yara Kim',
      },
      {
        id: 4,
        content: 'Good point! Yes, adding a few more would definitely help engage the audience.',
        createdAt: '2024-11-07T10:17:30Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Great, I’ll add some. Thanks for the feedback!',
        createdAt: '2024-11-07T10:18:15Z',
        sentBy: 'Yara Kim',
      },
    ],
  },
  {
    id: 10,
    name: 'Zane Patel',
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
    createdAt: '2024-11-07T11:25:50Z',
    email: 'zane.patel@example.com',
    phone: '+1 234 567 8912',
    messages: [
      {
        id: 1,
        content: 'Good morning, John!',
        createdAt: '2024-11-07T11:25:50Z',
        sentBy: 'Zane Patel',
      },
      {
        id: 2,
        content: 'Morning, Zane! How’s everything going?',
        createdAt: '2024-11-07T11:26:15Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'All good here! Just wanted to confirm the meeting time for tomorrow.',
        createdAt: '2024-11-07T11:26:45Z',
        sentBy: 'Zane Patel',
      },
      {
        id: 4,
        content: 'Sure, it’s set for 10 AM. Will you be able to make it?',
        createdAt: '2024-11-07T11:27:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Yes, perfect timing. Thanks, John!',
        createdAt: '2024-11-07T11:27:40Z',
        sentBy: 'Zane Patel',
      },
    ],
  },
  {
    id: 18,
    name: 'Victor Adams',
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
    createdAt: '2024-11-07T11:30:19Z',
    email: 'victor.adams@example.com',
    phone: '+1 234 567 8910',
    messages: [
      {
        id: 1,
        content: 'Hey John! Can I ask a quick question?',
        createdAt: '2024-11-07T11:30:19Z',
        sentBy: 'Victor Adams',
      },
      {
        id: 2,
        content: 'Of course, Victor. What do you need?',
        createdAt: '2024-11-07T11:31:00Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Just wondering if we’re still on track for the release next week.',
        createdAt: '2024-11-07T11:31:30Z',
        sentBy: 'Victor Adams',
      },
      {
        id: 4,
        content: 'Yes, everything is on schedule! Just a few more tests to go.',
        createdAt: '2024-11-07T11:32:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Sounds great, thanks for the update!',
        createdAt: '2024-11-07T11:32:45Z',
        sentBy: 'Victor Adams',
      },
    ],
  },
  {
    id: 19,
    name: 'Wendy Lee',
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
    createdAt: '2024-11-08T09:52:33Z',
    email: 'wendy.lee@example.com',
    phone: '+1 234 567 8911',
    messages: [
      {
        id: 1,
        content: 'Good morning, John!',
        createdAt: '2024-11-08T09:52:33Z',
        sentBy: 'Wendy Lee',
      },
      {
        id: 2,
        content: 'Morning, Wendy! How can I help?',
        createdAt: '2024-11-08T09:53:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Just checking if the report has been finalized yet.',
        createdAt: '2024-11-08T09:54:00Z',
        sentBy: 'Wendy Lee',
      },
      {
        id: 4,
        content: 'Yes, I finished it yesterday. I’ll send it over shortly.',
        createdAt: '2024-11-08T09:54:35Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Perfect, thanks so much!',
        createdAt: '2024-11-08T09:55:10Z',
        sentBy: 'Wendy Lee',
      },
    ],
  },
  {
    id: 20,
    name: 'Xander Brown',
    image: 'https://randomuser.me/api/portraits/men/10.jpg',
    createdAt: '2024-11-09T13:45:24Z',
    email: 'xander.brown@example.com',
    phone: '+1 234 567 8912',
    messages: [
      {
        id: 1,
        content: 'Hi John! Are we still meeting later?',
        createdAt: '2024-11-09T13:45:24Z',
        sentBy: 'Xander Brown',
      },
      {
        id: 2,
        content: 'Hey Xander! Yes, 3 PM as planned.',
        createdAt: '2024-11-09T13:46:00Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'Got it. Just wanted to confirm. Thanks!',
        createdAt: '2024-11-09T13:46:30Z',
        sentBy: 'Xander Brown',
      },
      {
        id: 4,
        content: 'No problem! See you then.',
        createdAt: '2024-11-09T13:47:00Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Looking forward to it!',
        createdAt: '2024-11-09T13:47:30Z',
        sentBy: 'Xander Brown',
      },
    ],
  },
  {
    id: 21,
    name: 'Yara Kim',
    image: 'https://randomuser.me/api/portraits/women/11.jpg',
    createdAt: '2024-11-07T10:15:20Z',
    email: 'yara.kim@example.com',
    phone: '+1 234 567 8913',
    messages: [
      {
        id: 1,
        content: 'Hi John! Do you have a minute to chat?',
        createdAt: '2024-11-07T10:15:20Z',
        sentBy: 'Yara Kim',
      },
      {
        id: 2,
        content: 'Hey Yara! Sure, what’s up?',
        createdAt: '2024-11-07T10:16:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content:
          'I had a question about the presentation slides. Do you think we need more visuals?',
        createdAt: '2024-11-07T10:16:45Z',
        sentBy: 'Yara Kim',
      },
      {
        id: 4,
        content: 'Good point! Yes, adding a few more would definitely help engage the audience.',
        createdAt: '2024-11-07T10:17:30Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Great, I’ll add some. Thanks for the feedback!',
        createdAt: '2024-11-07T10:18:15Z',
        sentBy: 'Yara Kim',
      },
    ],
  },
  {
    id: 22,
    name: 'Zane Patel',
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
    createdAt: '2024-11-07T11:25:50Z',
    email: 'zane.patel@example.com',
    phone: '+1 234 567 8914',
    messages: [
      {
        id: 1,
        content: 'Good morning, John!',
        createdAt: '2024-11-07T11:25:50Z',
        sentBy: 'Zane Patel',
      },
      {
        id: 2,
        content: 'Morning, Zane! How’s everything going?',
        createdAt: '2024-11-07T11:26:15Z',
        sentBy: 'John Doe',
      },
      {
        id: 3,
        content: 'All good here! Just wanted to confirm the meeting time for tomorrow.',
        createdAt: '2024-11-07T11:26:45Z',
        sentBy: 'Zane Patel',
      },
      {
        id: 4,
        content: 'Sure, it’s set for 10 AM. Will you be able to make it?',
        createdAt: '2024-11-07T11:27:10Z',
        sentBy: 'John Doe',
      },
      {
        id: 5,
        content: 'Yes, perfect timing. Thanks, John!',
        createdAt: '2024-11-07T11:27:40Z',
        sentBy: 'Zane Patel',
      },
    ],
  },
]
